### PR TITLE
Validate initial input value, offers context on what is wrong

### LINKED ISSUE #84: Validate initial input value, offer context on invalid values
When I run generate maven project the default value for artifact id is "MyQuarkusProject" and that gives two problems:

1) when pressing enter on it the wizard does not move forward nor does it highlight the artifact id is not allowed.
2) only when editing the field do you get an error highlighting the issue, but it just says "invalid artifact id" giving no hint on what is wrong - in this case seem to be that it has uppercase letters. 

So would be good to have the validation error shown immediately or at least when pressing Enter and then tell user what is actually wrong with the artifact id or say what a valid one would be.

### PR DESCRIPTION
**Pull request by xorye**
Fixes #84

The create project wizard will now validate the default value injected in the field:
validation gif

The error messages for invalid groupId, artifactId, package name etc. now provide context:
image
image

Also, I've noticed that there doesn't seem to be version validation for https://code.quarkus.io/. Is version something that should be validated for Maven projects in general?

Before, the version was validated against this regex:  `[A-Za-z0-9_-.]+$`

Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

File: src/generateProject/validateInput.ts [hunk 1]
```diff
@@ -47,15 +51,23 @@ export async function validatePackageName(userInput: string): Promise<string|und
...
+    } else if (!/[a-zA-Z\\d_$]$/.test(userInput)) {
+      return 'Invalid package name: A valid package name must end with characters from A to z, a number, or the following symbols: _$';
+    }
+    return 'Invalid package name: A valid package name can only contain characters from A to z and the following symbols: ._$';
   }
   return undefined;
 }
 
 export async function validateResourceName(userInput: string): Promise<string|undefined> {
   const re = new RegExp('^[A-Za-z]+[A-Za-z0-9_.]*$');
```
Comment (fbricon) [inline src/generateProject/validateInput.ts]: `.` is not a valid character for a resource name

File: src/generateProject/validateInput.ts [hunk 2]
```diff
@@ -47,15 +51,23 @@ export async function validatePackageName(userInput: string): Promise<string|und
...
   if (!re.test(userInput)) {
-    return 'Invalid resource name';
+    if (!/^[A-Za-z]/.test(userInput)) {
+      return 'Invalid resource name: A valid resource name must start with a character from A to z';
+    }
+    return 'Invalid resource name: A valid resource name can only contain characters from A to z, numbers, and the following symbols: ._';
```
Comment (fbricon) [inline src/generateProject/validateInput.ts]: `.` is not a valid character for a resource name

**Review by fbricon — CHANGES_REQUESTED** [review]

File: src/generateProject/validateInput.ts (hunk 1 above)
Comment (xorye) [reply src/generateProject/validateInput.ts]: Did you mean package name?

Comment (fbricon) [reply src/generateProject/validateInput.ts]: no, resource (aka class) name

**Comment by xorye** [comment]
fixed

**Review by fbricon — APPROVED** [review]
